apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-vela-app
spec:
  components:
    - name: osrm-frontend
      type: webservice
      properties:
        image: osrm/osrm-frontend
        # Open container port 9966, expose it via NodePort 31111
        ports:
          - port: 9966       # containerPort
            expose: true     # turn on Service creation
            nodePort: 32222  # request this specific NodePort
        exposeType: NodePort # Service type
      traits:
        - type: env
          properties:
            env:
              ENV_VAR: "production"
